### ISSUE TITLE
On Tabs removal or tabs addition the tabs component are wrapping without showing 'show more' icon

### ISSUE THREAD

**Issue by thanmaic** [maslianok/react-responsive-tabs#89] opened 2021-04-20 04:49 UTC
@maslianok @dcworldwide  I still face the same issue even on the latest code. Please help resolve it.
I am using the Tabs Removal example. But still face this issue of tabs wrapping to new line below instead of showing the '...' .

```
onRemoveTab = (key, evt) => {
    evt.stopPropagation();

    // current tabs
    const { items } = this.state;

    // find index to remove
    const indexToRemove = items.findIndex((tab) => tab.key === key);

    // create a new array without [indexToRemove] item
    const newTabs = [
      ...items.slice(0, indexToRemove),
      ...items.slice(indexToRemove + 1),
    ];

    const nextSelectedIndex = newTabs[indexToRemove]
      ? indexToRemove
      : indexToRemove - 1;

    if (!newTabs[nextSelectedIndex]) {
      alert("You can not delete the last tab!");
      return;
    }

      this.setState({
        items: newTabs,
        selectedTabKey: newTabs[nextSelectedIndex].key,
      });
  };

getTabs = () => {
    return dummyData.map((president, index) => ({
      key: index,
      title: president.name,
      getContent: () => president.biography,
      tabClassName: "tab-wrapper",
      tabClassName: "tab",
      panelClassName: "panel",
    }));
  };

<div className="itemRemoval__wrapper" style={{ marginTop: 120 }}>
        <Tabs
          items={this.state.items}
          selectedTabKey={this.state.selectedTabKey}
          allowRemove
          removeActiveOnly
          onRemove={this.onRemoveTab}
          transform={false}
          showMore={true}
          uid={uniqueId()}
        />
 </div>

```

<img width="1190" alt="Screenshot 2021-04-19 at 11 02 22 PM" src="https://user-images.githubusercontent.com/50735542/115278635-4ff19a00-a163-11eb-97a2-254b5e6f5110.png">

What changes need to be done or any workaround for this issue?

I am using react: "^17.0.1"
react-responsive-tabs: "^4.4.0"
react-resize-detector: "^6.6.5"

I am testing on MacBook Chrome browser.

**Comment by maslianok** [comment] 2021-04-23 08:44
@thanmaic Thanks for reporting the issue.

Can I ask you to create a codesandbox example that reproduces the bug?

Something like I've created earlier https://codesandbox.io/s/dazzling-wing-lys8h?file=/src/Tab.js

From the first look, I suppose you have some wrong wrapper styles (`itemRemoval__wrapper` or upper parents) that prevent the library to measure block width. But it's hard to say for sure - I don't see the full picture and I can't reproduce the bug

**Comment by thanmaic** [comment] 2021-04-23 09:30
This is the same code as in here https://github.com/maslianok/react-responsive-tabs/tree/master/examples/src/TabsRemoval.
When i tried to execute the same in my project i got the issue as shared above.

I tried to remove the itemRemoval__wrapper style as well, but i run into same issue.

**Comment by maslianok** [comment] 2021-04-23 10:24
Please, create an example at codesandbox.io or any other online sandbox

**Comment by thanmaic** [comment] 2021-04-23 10:42
Hi @maslianok,
Here is the example on codesandbox https://codesandbox.io/s/interesting-oskar-uyy15?file=/src/Example.js
Please check and help me out to resolve the issue.

**Comment by thanmaic** [comment] 2021-04-23 10:54
<img width="1792" alt="Screenshot 2021-04-23 at 4 22 01 PM" src="https://user-images.githubusercontent.com/50735542/115861137-0c8f7800-a450-11eb-92c9-d1d3695eafb5.png">

In the above Example code when i try to select the tabs and when i try to delete any of the tabs it would lead to something like this in the above screenshot.
The expected is that I select different tabs or i delete any the show more button should be showed without showing all the tabs.

Please check the code and help me out to resolve the issue at the earliest. Thanks

**Comment by maslianok** [comment] 2021-04-23 10:55
@thanmaic that's what I see when I open your link

<img width="868" alt="Screenshot 2021-04-23 at 13 50 51" src="https://user-images.githubusercontent.com/3485490/115861039-f925e200-a43a-11eb-92a6-f19bdceb8405.png">

There must be some problem with styles. Please, don't rush and check everything.

Check that everything works and you see the bug you described in the issue.

Don't worry, I would help you if we prove that the bug caused by the library, but I won't fix your code instead of you, deal?

**Comment by maslianok** [comment] 2021-04-23 10:57
Ok, great 👍 

we finally found the problem :) The tab should be deleted in order to reproduce the bug.

I'll work on it

**Comment by thanmaic** [comment] 2021-04-23 11:03
Ok sure. 

This issue/problem happens in 3 scenarios: 1.) when i try to switch from one tab to another, 2.) when i try to delete the tab, 3.) when i try to add a new tab to the array.

Any expected time frame to fix it, as this is something priority in my list? Please let me know once it is fixed and working.  
Even i will give it a try. :)

Thanks

**Comment by thanmaic** [comment] 2021-04-25 05:12
@maslianok Any update on the fix or any workaround for this issue?

**Comment by maslianok** [comment] 2021-04-27 12:21
@thanmaic fixed in v4.4.1

**Comment by maslianok** [comment] 2021-04-27 12:21
Thank you for your feedback 👍

**Closed by maslianok** 2021-04-27 12:21 UTC

**Comment by thanmaic** [comment] 2021-05-03 05:17
@maslianok The issue seems fixed. Thanks

Just curious to know when I add the library in my project it does work as expected. But when i try to download the library and copy the src/ folder to my project as I need some customisation on things it doesn't work as expected. I did install react-resize detector as well.

Any reason why it doesn't work or anything more to be done along with it?

**Comment by maslianok** [comment] 2021-05-07 14:58
`src` is the source code. Your app uses the `lib` folder when you install `react-responsive-tabs` via npm or yarn.

`lib` is the transpiled version of `src` with help of webpack and webpack config (`.babelrc`). You must use the same plugins in order to achieve the same result

**Comment by thanmaic** [comment] 2021-05-07 15:01
Could you please advice me on the steps to follow as to run the code from my local instead of npm library as i need some customisations in it?

**Comment by maslianok** [comment] 2021-05-07 15:10
There is no simple answer. You're trying to use the library in a way it was not designed to be used. And I have no manual on what should you do to directly inject it into your codebase.
